// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: migration.proto

package migration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload_OtpParameters_Algorithm int32

const (
	Payload_OtpParameters_ALGORITHM_UNSPECIFIED Payload_OtpParameters_Algorithm = 0
	Payload_OtpParameters_ALGORITHM_SHA1        Payload_OtpParameters_Algorithm = 1
	Payload_OtpParameters_ALGORITHM_SHA256      Payload_OtpParameters_Algorithm = 2
	Payload_OtpParameters_ALGORITHM_SHA512      Payload_OtpParameters_Algorithm = 3
	Payload_OtpParameters_ALGORITHM_MD5         Payload_OtpParameters_Algorithm = 4
)

// Enum value maps for Payload_OtpParameters_Algorithm.
var (
	Payload_OtpParameters_Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_SHA1",
		2: "ALGORITHM_SHA256",
		3: "ALGORITHM_SHA512",
		4: "ALGORITHM_MD5",
	}
	Payload_OtpParameters_Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_SHA1":        1,
		"ALGORITHM_SHA256":      2,
		"ALGORITHM_SHA512":      3,
		"ALGORITHM_MD5":         4,
	}
)

func (x Payload_OtpParameters_Algorithm) Enum() *Payload_OtpParameters_Algorithm {
	p := new(Payload_OtpParameters_Algorithm)
	*p = x
	return p
}

func (x Payload_OtpParameters_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payload_OtpParameters_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[0].Descriptor()
}

func (Payload_OtpParameters_Algorithm) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[0]
}

func (x Payload_OtpParameters_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payload_OtpParameters_Algorithm.Descriptor instead.
func (Payload_OtpParameters_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Payload_OtpParameters_DigitCount int32

const (
	Payload_OtpParameters_DIGIT_COUNT_UNSPECIFIED Payload_OtpParameters_DigitCount = 0
	Payload_OtpParameters_DIGIT_COUNT_SIX         Payload_OtpParameters_DigitCount = 1
	Payload_OtpParameters_DIGIT_COUNT_EIGHT       Payload_OtpParameters_DigitCount = 2
)

// Enum value maps for Payload_OtpParameters_DigitCount.
var (
	Payload_OtpParameters_DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "DIGIT_COUNT_SIX",
		2: "DIGIT_COUNT_EIGHT",
	}
	Payload_OtpParameters_DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"DIGIT_COUNT_SIX":         1,
		"DIGIT_COUNT_EIGHT":       2,
	}
)

func (x Payload_OtpParameters_DigitCount) Enum() *Payload_OtpParameters_DigitCount {
	p := new(Payload_OtpParameters_DigitCount)
	*p = x
	return p
}

func (x Payload_OtpParameters_DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payload_OtpParameters_DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[1].Descriptor()
}

func (Payload_OtpParameters_DigitCount) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[1]
}

func (x Payload_OtpParameters_DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payload_OtpParameters_DigitCount.Descriptor instead.
func (Payload_OtpParameters_DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0, 1}
}

type Payload_OtpParameters_OtpType int32

const (
	Payload_OtpParameters_OTP_TYPE_UNSPECIFIED Payload_OtpParameters_OtpType = 0
	Payload_OtpParameters_OTP_TYPE_HOTP        Payload_OtpParameters_OtpType = 1
	Payload_OtpParameters_OTP_TYPE_TOTP        Payload_OtpParameters_OtpType = 2
)

// Enum value maps for Payload_OtpParameters_OtpType.
var (
	Payload_OtpParameters_OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "OTP_TYPE_HOTP",
		2: "OTP_TYPE_TOTP",
	}
	Payload_OtpParameters_OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"OTP_TYPE_HOTP":        1,
		"OTP_TYPE_TOTP":        2,
	}
)

func (x Payload_OtpParameters_OtpType) Enum() *Payload_OtpParameters_OtpType {
	p := new(Payload_OtpParameters_OtpType)
	*p = x
	return p
}

func (x Payload_OtpParameters_OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payload_OtpParameters_OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[2].Descriptor()
}

func (Payload_OtpParameters_OtpType) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[2]
}

func (x Payload_OtpParameters_OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payload_OtpParameters_OtpType.Descriptor instead.
func (Payload_OtpParameters_OtpType) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0, 2}
}

type Payload struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OtpParameters []*Payload_OtpParameters `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	Version       int32                    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BatchSize     int32                    `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex    int32                    `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	BatchId       int32                    `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetOtpParameters() []*Payload_OtpParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *Payload) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Payload) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *Payload) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *Payload) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type Payload_OtpParameters struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Secret        []byte                           `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name          string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                           `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm     Payload_OtpParameters_Algorithm  `protobuf:"varint,4,opt,name=algorithm,proto3,enum=migration.Payload_OtpParameters_Algorithm" json:"algorithm,omitempty"`
	Digits        Payload_OtpParameters_DigitCount `protobuf:"varint,5,opt,name=digits,proto3,enum=migration.Payload_OtpParameters_DigitCount" json:"digits,omitempty"`
	Type          Payload_OtpParameters_OtpType    `protobuf:"varint,6,opt,name=type,proto3,enum=migration.Payload_OtpParameters_OtpType" json:"type,omitempty"`
	Counter       uint64                           `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
	UniqueId      string                           `protobuf:"bytes,8,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload_OtpParameters) Reset() {
	*x = Payload_OtpParameters{}
	mi := &file_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload_OtpParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_OtpParameters) ProtoMessage() {}

func (x *Payload_OtpParameters) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_OtpParameters.ProtoReflect.Descriptor instead.
func (*Payload_OtpParameters) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payload_OtpParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Payload_OtpParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payload_OtpParameters) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Payload_OtpParameters) GetAlgorithm() Payload_OtpParameters_Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Payload_OtpParameters_ALGORITHM_UNSPECIFIED
}

func (x *Payload_OtpParameters) GetDigits() Payload_OtpParameters_DigitCount {
	if x != nil {
		return x.Digits
	}
	return Payload_OtpParameters_DIGIT_COUNT_UNSPECIFIED
}

func (x *Payload_OtpParameters) GetType() Payload_OtpParameters_OtpType {
	if x != nil {
		return x.Type
	}
	return Payload_OtpParameters_OTP_TYPE_UNSPECIFIED
}

func (x *Payload_OtpParameters) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Payload_OtpParameters) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

var File_migration_proto protoreflect.FileDescriptor

const file_migration_proto_rawDesc = "" +
	"\n" +
	"\x0fmigration.proto\x12\tmigration\"\xbe\x06\n" +
	"\aPayload\x12G\n" +
	"\x0eotp_parameters\x18\x01 \x03(\v2 .migration.Payload.OtpParametersR\rotpParameters\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbatch_index\x18\x04 \x01(\x05R\n" +
	"batchIndex\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\x05R\abatchId\x1a\xf4\x04\n" +
	"\rOtpParameters\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12H\n" +
	"\talgorithm\x18\x04 \x01(\x0e2*.migration.Payload.OtpParameters.AlgorithmR\talgorithm\x12C\n" +
	"\x06digits\x18\x05 \x01(\x0e2+.migration.Payload.OtpParameters.DigitCountR\x06digits\x12<\n" +
	"\x04type\x18\x06 \x01(\x0e2(.migration.Payload.OtpParameters.OtpTypeR\x04type\x12\x18\n" +
	"\acounter\x18\a \x01(\x04R\acounter\x12\x1b\n" +
	"\tunique_id\x18\b \x01(\tR\buniqueId\"y\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eALGORITHM_SHA1\x10\x01\x12\x14\n" +
	"\x10ALGORITHM_SHA256\x10\x02\x12\x14\n" +
	"\x10ALGORITHM_SHA512\x10\x03\x12\x11\n" +
	"\rALGORITHM_MD5\x10\x04\"U\n" +
	"\n" +
	"DigitCount\x12\x1b\n" +
	"\x17DIGIT_COUNT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIGIT_COUNT_SIX\x10\x01\x12\x15\n" +
	"\x11DIGIT_COUNT_EIGHT\x10\x02\"I\n" +
	"\aOtpType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOTP_TYPE_HOTP\x10\x01\x12\x11\n" +
	"\rOTP_TYPE_TOTP\x10\x02B$Z\"github.com/dim13/otpauth/migrationb\x06proto3"

var (
	file_migration_proto_rawDescOnce sync.Once
	file_migration_proto_rawDescData []byte
)

func file_migration_proto_rawDescGZIP() []byte {
	file_migration_proto_rawDescOnce.Do(func() {
		file_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)))
	})
	return file_migration_proto_rawDescData
}

var file_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_migration_proto_goTypes = []any{
	(Payload_OtpParameters_Algorithm)(0),  // 0: migration.Payload.OtpParameters.Algorithm
	(Payload_OtpParameters_DigitCount)(0), // 1: migration.Payload.OtpParameters.DigitCount
	(Payload_OtpParameters_OtpType)(0),    // 2: migration.Payload.OtpParameters.OtpType
	(*Payload)(nil),                       // 3: migration.Payload
	(*Payload_OtpParameters)(nil),         // 4: migration.Payload.OtpParameters
}
var file_migration_proto_depIdxs = []int32{
	4, // 0: migration.Payload.otp_parameters:type_name -> migration.Payload.OtpParameters
	0, // 1: migration.Payload.OtpParameters.algorithm:type_name -> migration.Payload.OtpParameters.Algorithm
	1, // 2: migration.Payload.OtpParameters.digits:type_name -> migration.Payload.OtpParameters.DigitCount
	2, // 3: migration.Payload.OtpParameters.type:type_name -> migration.Payload.OtpParameters.OtpType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_migration_proto_init() }
func file_migration_proto_init() {
	if File_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_proto_goTypes,
		DependencyIndexes: file_migration_proto_depIdxs,
		EnumInfos:         file_migration_proto_enumTypes,
		MessageInfos:      file_migration_proto_msgTypes,
	}.Build()
	File_migration_proto = out.File
	file_migration_proto_goTypes = nil
	file_migration_proto_depIdxs = nil
}
